[package]
name = "c32"
version = "0.1.0"
authors = ["tjj <1804232963@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
